apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: k8s-notification-operator-system
data:
  discordBotToken: "<YOUR_DISCORD_BOT_TOKEN>"
  discordChannelID: "<YOUR_DISCORD_CHANNEL_ID>"
  watchNamespaces: "default,custom-namespace"